CREATE DATABASE VacationManager

USE VacationManager

CREATE TABLE ConfirmRegistrationCode (
	Id UNIQUEIDENTIFIER NOT NULL,
	Code VARCHAR(10) NOT NULL,
	ExpirationDate DATE DEFAULT dateadd(month,1,getdate()),
	CONSTRAINT PK_ConfirmRegistrationCode PRIMARY KEY (Id)
)

CREATE TABLE [User] (
	Id UNIQUEIDENTIFIER NOT NULL,
	ConfirmRegistrationCodeId UNIQUEIDENTIFIER NOT NULL,
	Email VARCHAR(100) NOT NULL,
	[Password] VARCHAR(100) NOT NULL,
	PasswordSalt VARCHAR(100) NOT NULL,
	[Role] INT NOT NULL,
	IsBanned BIT DEFAULT 0,
	IsConfirmed BIT DEFAULT 0,
	RegistrationDate DATE DEFAULT GETDATE(),
	CONSTRAINT PK_User PRIMARY KEY (Id),
	CONSTRAINT FK_UserConfirmRegistrationCode FOREIGN KEY (ConfirmRegistrationCodeId) REFERENCES ConfirmRegistrationCode(Id)
)

CREATE TABLE PropertyType (
	Id UNIQUEIDENTIFIER NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	CONSTRAINT PK_PropertyType PRIMARY KEY (Id)
)

CREATE TABLE Country (
	Id UNIQUEIDENTIFIER  NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Country PRIMARY KEY (Id),
)

CREATE TABLE Town (
	Id UNIQUEIDENTIFIER  NOT NULL,
	CountryId UNIQUEIDENTIFIER  NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Town PRIMARY KEY (Id),
	CONSTRAINT FK_TownCountry FOREIGN KEY (CountryId) REFERENCES Country(Id)
)

CREATE TABLE Property (
	Id UNIQUEIDENTIFIER NOT NULL,
	OwnerId UNIQUEIDENTIFIER NOT NULL,
	TownId UNIQUEIDENTIFIER NOT NULL,
	PropertyTypeId UNIQUEIDENTIFIER NOT NULL,
	[Address] NVARCHAR(100) NOT NULL,
	TelephoneNumber VARCHAR(50) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(500),
	OpenFrom DATE,
	OpenTo DATE,
	IsOpenedAllYear BIT NOT NULL,
	CONSTRAINT PK_Property PRIMARY KEY (Id),
	CONSTRAINT FK_PropertyUser FOREIGN KEY (OwnerId) REFERENCES [User](Id),
	CONSTRAINT FK_PropertyTown FOREIGN KEY (TownId) REFERENCES Town(Id),
	CONSTRAINT FK_PropertyPropertyType FOREIGN KEY (PropertyTypeId) REFERENCES PropertyType(Id)
)

CREATE TABLE PropertyUnitType (
	Id UNIQUEIDENTIFIER NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	Capacity INT NOT NULL
	CONSTRAINT PK_PropertyUnitType PRIMARY KEY (Id)
)

CREATE TABLE PropertyUnit (
	Id UNIQUEIDENTIFIER NOT NULL,
	PropertyId UNIQUEIDENTIFIER NOT NULL,
	PropertyUnitTypeId UNIQUEIDENTIFIER NOT NULL,
	NightPrice DECIMAL(8, 2) NOT NULL,
	CONSTRAINT PK_PropertyUnit PRIMARY KEY (Id),
	CONSTRAINT FK_PropertyUnitProperty FOREIGN KEY (PropertyId) REFERENCES Property(Id),
	CONSTRAINT FK_PropertyUnitPropertyUnitType FOREIGN KEY (PropertyUnitTypeId) REFERENCES PropertyUnitType(Id)
)

CREATE TABLE Reservation (
	Id UNIQUEIDENTIFIER NOT NULL,
	PropertyUnitId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	Paid BIT DEFAULT 0,
	DueAmount DECIMAL(10, 2) NOT NULL,
	CONSTRAINT PK_Reservation PRIMARY KEY (Id),
	CONSTRAINT FK_ReservationPropertyUnit FOREIGN KEY (PropertyUnitId) REFERENCES PropertyUnit(Id),
	CONSTRAINT FK_ReservationUser FOREIGN KEY (UserId) REFERENCES [User](Id)
)

CREATE TABLE Review (
	Id UNIQUEIDENTIFIER NOT NULL,
	PropertyId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	OveralRating DECIMAL(3,1) NOT NULL, 
	LocationRating DECIMAL(3,1),
	ComfortRating DECIMAL(3,1),
	CleanlinessRating DECIMAL(3,1),
	Comment NVARCHAR(500),
	CONSTRAINT PK_Review PRIMARY KEY (Id),
	CONSTRAINT FK_ReviewProperty FOREIGN KEY (PropertyId) REFERENCES Property(Id),
	CONSTRAINT FK_ReviewUser FOREIGN KEY (UserId) REFERENCES [User](Id),
)

CREATE TABLE DiscountCode (
	Id UNIQUEIDENTIFIER NOT NULL,
	PropertyId UNIQUEIDENTIFIER NOT NULL,
	DiscountPercent INT NOT NULL,
	ValidFrom DATETIME NOT NULL,
	ValidTo DATETIME,
	CONSTRAINT PK_DiscountCode PRIMARY KEY (Id),
	CONSTRAINT FK_DiscountCodeProperty FOREIGN KEY (PropertyId) REFERENCES Property(Id),
)

CREATE TABLE [Image] (
	Id UNIQUEIDENTIFIER NOT NULL,
	PropertyId UNIQUEIDENTIFIER NOT NULL,
	SourcePath NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_Image PRIMARY KEY (Id),
	CONSTRAINT FK_ImageProperty FOREIGN KEY (PropertyId) REFERENCES Property(Id),
)

CREATE TABLE Facility (
	Id UNIQUEIDENTIFIER NOT NULL,
	Facility VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Facility PRIMARY KEY (Id),
)

CREATE TABLE PropertyFacility (
	PropertyId UNIQUEIDENTIFIER NOT NULL,
	FacilityId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_PropertyFacility PRIMARY KEY (PropertyId, FacilityId),
	CONSTRAINT FK_PropertyFacilityProperty FOREIGN KEY (PropertyId) REFERENCES Property(Id),
	CONSTRAINT FK_PropertyFacilityFacility FOREIGN KEY (FacilityId) REFERENCES Facility(Id)
)
